apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcgapp
  labels:
    app: qcgapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qcgapp
  template:
    metadata:
      labels:
        app: qcgapp
    spec:
      containers:
        - name: qcgcontainer
          image: bmicontainer.azurecr.io/bmicalculator:latest
          imagePullPolicy: Always
          ports:  # Correct indentation here
            - containerPort: 80
