apiVersion: v1
kind: Service
metadata:
  name: qcg-service
spec:
  selector:
    app: qcg-app
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Container port
  type: LoadBalancer  # For external access
